- name: core-tools - Update repos...
  become: true
  apt:
    update_cache: yes

- name: core-tools - Install wget...
  become: true
  apt:
    name: wget

- name: core-tools - Install curl...
  become: true
  apt:
    name: curl

- name: core-tools - Install git...
  become: true
  apt:
    name: git

- name: core-tools - Install htop...
  become: true
  apt:
    name: htop

- name: core-tools - Install tmux...
  become: true
  apt:
    name: tmux

- name: core-tools - Install neofetch...
  become: true
  apt:
    name: neofetch

- name: core-tools - Install mc...
  become: true
  apt:
    name: mc

- name: core-tools - Install xclip...
  become: true
  apt:
    name: xclip

- name: core-tools - Install cmake make gcc clang g++ cargo...
  become: true
  apt:
    name: ["cmake", "make", "gcc", "clang", "g++", "cargo"]

- name: Creates directory {{ dirDownload }}...
  file:
    path: "{{ dirDownload }}"
    state: directory
