- name: nvim - Get deb package...
  become: false 
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb
    dest: "{{ dirDownload }}/nvim-linux64.deb"

- name: nvim - Install nvim0.8.0...
  become: true
  shell: "apt install {{ dirDownload }}/nvim-linux64.deb"
