- name: ZSH - Install zsh...
  become: true
  apt: 
    name: zsh

- name: ZSH - Change shell...
  become: yes
  replace: 
    path: /etc/passwd
    regexp: '\/home\/{{ username }}:\/bin\/bash'
    replace: '/home/{{ username }}:/bin/zsh'

- name: Oh-my-zsh - Download script...
  become: false
  shell: "curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh > {{ dirDownload }}/oh-my-zsh.sh"

- name: Oh-my-zsh - Chmod +x {{ dirDownload }}/oh-my-zsh.sh...
  become: true
  shell: "chmod +x {{ dirDownload }}/oh-my-zsh.sh"

- name: Oh-my-zsh - Install...
  become: yes
  become_user: "{{ username }}"
  shell: "{{ dirDownload }}/oh-my-zsh.sh"

- name: Oh-my-zsh - Install zsh-autosuggestions...
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "/home/{{ username }}/.oh-my-zsh/plugins/zsh-autosuggestions"